// ─────────────────────────────────────────────────────────────────
// AUTO-GENERATED by Supabase CLI in Phase 2
// Command: npx supabase gen types typescript --project-id ckmhvsrfodyaqizuqcyy > src/types/database.types.ts
//
// For now this is a placeholder so the app compiles.
// Replace entirely after running migrations in Phase 2.
// ─────────────────────────────────────────────────────────────────

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Populated after Phase 2 migrations
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: 'admin' | 'frontdesk' | 'salesrep' | 'technician'
      lead_stage:
        | 'new_lead'
        | 'qualifying'
        | 'qualified'
        | 'site_visit_scheduled'
        | 'proposal_in_progress'
        | 'quote_sent'
        | 'agreement_signed'
        | 'won'
        | 'lost'
        | 'future_follow_up'
        | 'dnd'
      job_stage: 'scheduled' | 'waiting_for_stock' | 'in_progress' | 'complete'
      customer_stage: 'active' | 'service_due' | 'renewal_due' | 'upsell' | 'at_risk'
      invoice_type: 'deposit' | 'final' | 'commission' | 'rental' | 'maintenance' | 'filter_sale'
      invoice_status: 'pending' | 'paid' | 'failed' | 'overdue'
      payment_method: 'cash' | 'card' | 'ach' | 'hearth_finance'
      // Lead-specific enums (pipeline upgrade v2)
      payment_method_enum: 'cash' | 'check' | 'card' | 'financing'
      install_preference_enum: 'asap' | 'specific_date' | 'flexible'
      lead_event_type_enum:
        | 'lead_created'
        | 'stage_change'
        | 'call_logged'
        | 'note_added'
        | 'agreement_signed'
        | 'job_created'
        | 'lead_lost'
        | 'lead_dnd'
        | 'lead_followup'
        | 'field_updated'
        | 'rep_changed'
      // Dispatch module enums
      job_status_enum: 'scheduled' | 'waiting_for_stock' | 'in_progress' | 'complete'
      job_type_enum: 'standard_install' | 'service' | 'warranty' | 'filter_change' | 'rental_setup'
      system_type_enum: 'softener_only' | 'pure_start_softener' | 'advanced_softener' | 'dual_tank' | 'ro_install' | 'combo_whole_home_ro'
      job_event_type_enum: 'job_created' | 'status_change' | 'tech_assigned' | 'checklist_item_completed' | 'tech_verification' | 'photo_uploaded' | 'handover_submitted' | 'consent_submitted' | 'job_completed' | 'note_added'
      form_type_enum: 'whole_home_handover' | 'ro_handover' | 'ro_drilling_consent'
      form_status_enum: 'pending' | 'completed'
      photo_category_enum: 'before_install' | 'after_install' | 'equipment' | 'plumbing' | 'general'
      checklist_section_enum: 'pre_installation' | 'system_installation' | 'programming' | 'final_testing' | 'cleanup' | 'photo_requirements' | 'technician_verification'
      water_source: 'municipal' | 'well' | 'spring'
      quote_type: 'purchase' | 'rental'
    }
  }
}
